/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ApolloAllAgents {
    'renderer': import('stencil-apollo').QueryRenderer<AllAgentsQuery, AllAgentsQueryVariables>;
  }
  interface ApolloUpdateAgent {
    'renderer': import('stencil-apollo').MutationRenderer<UpdateAgentMutation, UpdateAgentMutationVariables>;
  }
  interface ListAllAgents {
    'first': string;
    'last': string;
  }
}

declare global {


  interface HTMLApolloAllAgentsElement extends Components.ApolloAllAgents, HTMLStencilElement {}
  const HTMLApolloAllAgentsElement: {
    prototype: HTMLApolloAllAgentsElement;
    new (): HTMLApolloAllAgentsElement;
  };

  interface HTMLApolloUpdateAgentElement extends Components.ApolloUpdateAgent, HTMLStencilElement {}
  const HTMLApolloUpdateAgentElement: {
    prototype: HTMLApolloUpdateAgentElement;
    new (): HTMLApolloUpdateAgentElement;
  };

  interface HTMLListAllAgentsElement extends Components.ListAllAgents, HTMLStencilElement {}
  const HTMLListAllAgentsElement: {
    prototype: HTMLListAllAgentsElement;
    new (): HTMLListAllAgentsElement;
  };
  interface HTMLElementTagNameMap {
    'apollo-all-agents': HTMLApolloAllAgentsElement;
    'apollo-update-agent': HTMLApolloUpdateAgentElement;
    'list-all-agents': HTMLListAllAgentsElement;
  }
}

declare namespace LocalJSX {
  interface ApolloAllAgents {
    'renderer'?: import('stencil-apollo').QueryRenderer<AllAgentsQuery, AllAgentsQueryVariables>;
  }
  interface ApolloUpdateAgent {
    'renderer'?: import('stencil-apollo').MutationRenderer<UpdateAgentMutation, UpdateAgentMutationVariables>;
  }
  interface ListAllAgents {
    'first'?: string;
    'last'?: string;
  }

  interface IntrinsicElements {
    'apollo-all-agents': ApolloAllAgents;
    'apollo-update-agent': ApolloUpdateAgent;
    'list-all-agents': ListAllAgents;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'apollo-all-agents': LocalJSX.ApolloAllAgents & JSXBase.HTMLAttributes<HTMLApolloAllAgentsElement>;
      'apollo-update-agent': LocalJSX.ApolloUpdateAgent & JSXBase.HTMLAttributes<HTMLApolloUpdateAgentElement>;
      'list-all-agents': LocalJSX.ListAllAgents & JSXBase.HTMLAttributes<HTMLListAllAgentsElement>;
    }
  }
}


