/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ApolloAllAgents {
    'renderer': import('stencil-apollo').QueryRenderer<AllAgentsQuery, AllAgentsQueryVariables>;
  }
  interface ApolloAllAges {
    'renderer': import('stencil-apollo').QueryRenderer<AllAgesQuery, AllAgesQueryVariables>;
  }
  interface ApolloIncrementAge {
    'renderer': import('stencil-apollo').MutationRenderer<IncrementAgeMutation, IncrementAgeMutationVariables>;
  }
  interface ListAllAgents {
    'first': string;
    'last': string;
  }
  interface ListAllAges {
    'testProp': string;
  }
}

declare global {


  interface HTMLApolloAllAgentsElement extends Components.ApolloAllAgents, HTMLStencilElement {}
  const HTMLApolloAllAgentsElement: {
    prototype: HTMLApolloAllAgentsElement;
    new (): HTMLApolloAllAgentsElement;
  };

  interface HTMLApolloAllAgesElement extends Components.ApolloAllAges, HTMLStencilElement {}
  const HTMLApolloAllAgesElement: {
    prototype: HTMLApolloAllAgesElement;
    new (): HTMLApolloAllAgesElement;
  };

  interface HTMLApolloIncrementAgeElement extends Components.ApolloIncrementAge, HTMLStencilElement {}
  const HTMLApolloIncrementAgeElement: {
    prototype: HTMLApolloIncrementAgeElement;
    new (): HTMLApolloIncrementAgeElement;
  };

  interface HTMLListAllAgentsElement extends Components.ListAllAgents, HTMLStencilElement {}
  const HTMLListAllAgentsElement: {
    prototype: HTMLListAllAgentsElement;
    new (): HTMLListAllAgentsElement;
  };

  interface HTMLListAllAgesElement extends Components.ListAllAges, HTMLStencilElement {}
  const HTMLListAllAgesElement: {
    prototype: HTMLListAllAgesElement;
    new (): HTMLListAllAgesElement;
  };
  interface HTMLElementTagNameMap {
    'apollo-all-agents': HTMLApolloAllAgentsElement;
    'apollo-all-ages': HTMLApolloAllAgesElement;
    'apollo-increment-age': HTMLApolloIncrementAgeElement;
    'list-all-agents': HTMLListAllAgentsElement;
    'list-all-ages': HTMLListAllAgesElement;
  }
}

declare namespace LocalJSX {
  interface ApolloAllAgents {
    'renderer'?: import('stencil-apollo').QueryRenderer<AllAgentsQuery, AllAgentsQueryVariables>;
  }
  interface ApolloAllAges {
    'renderer'?: import('stencil-apollo').QueryRenderer<AllAgesQuery, AllAgesQueryVariables>;
  }
  interface ApolloIncrementAge {
    'renderer'?: import('stencil-apollo').MutationRenderer<IncrementAgeMutation, IncrementAgeMutationVariables>;
  }
  interface ListAllAgents {
    'first'?: string;
    'last'?: string;
  }
  interface ListAllAges {
    'testProp'?: string;
  }

  interface IntrinsicElements {
    'apollo-all-agents': ApolloAllAgents;
    'apollo-all-ages': ApolloAllAges;
    'apollo-increment-age': ApolloIncrementAge;
    'list-all-agents': ListAllAgents;
    'list-all-ages': ListAllAges;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'apollo-all-agents': LocalJSX.ApolloAllAgents & JSXBase.HTMLAttributes<HTMLApolloAllAgentsElement>;
      'apollo-all-ages': LocalJSX.ApolloAllAges & JSXBase.HTMLAttributes<HTMLApolloAllAgesElement>;
      'apollo-increment-age': LocalJSX.ApolloIncrementAge & JSXBase.HTMLAttributes<HTMLApolloIncrementAgeElement>;
      'list-all-agents': LocalJSX.ListAllAgents & JSXBase.HTMLAttributes<HTMLListAllAgentsElement>;
      'list-all-ages': LocalJSX.ListAllAges & JSXBase.HTMLAttributes<HTMLListAllAgesElement>;
    }
  }
}


